// Copyright Anton Vasserman, All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "GameplayTagContainer.h"
#include "NativeGameplayTags.h"

enum class ECL_FallType : uint8;
enum class ECL_Gait : uint8;
enum class ECL_Stance : uint8;
enum class ECL_TraversalAction : uint8;

namespace CLGameplayTags
{
	// Cheats
	CURSEDLANDS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cheat_Ability_WhiteMonster);
	
	// UI Layers
	CURSEDLANDS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Layer_Game);
	CURSEDLANDS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Layer_Menu);
	CURSEDLANDS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Layer_Modal);

	// InputTags
	CURSEDLANDS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move_Gamepad);
	CURSEDLANDS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move_KeyboardAndMouse);
	CURSEDLANDS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);

	// InputTags Abilities
	CURSEDLANDS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Ability);
	
	// Statuses
	CURSEDLANDS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Alive);
	CURSEDLANDS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Dead);
	CURSEDLANDS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Victorious);
	
	// Attributes
	CURSEDLANDS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes);

	// General Attributes
	CURSEDLANDS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_General_Health);
	CURSEDLANDS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_General_MaxHealth);
	CURSEDLANDS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_General_Mana);
	CURSEDLANDS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_General_MaxMana);
	CURSEDLANDS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_General_Stamina);
	CURSEDLANDS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_General_MaxStamina);

	// Resource Attributes
	CURSEDLANDS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Resource_Health_Full);
	CURSEDLANDS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Resource_Health_Normal);
	CURSEDLANDS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Resource_Health_Critical);
	CURSEDLANDS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Resource_Health_Depleted);
	CURSEDLANDS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Resource_Health_Infinite);
	CURSEDLANDS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Resource_Mana_Full);
	CURSEDLANDS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Resource_Mana_Normal);
	CURSEDLANDS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Resource_Mana_Critical);
	CURSEDLANDS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Resource_Mana_Depleted);
	CURSEDLANDS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Resource_Mana_Infinite);
	CURSEDLANDS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Resource_Stamina_Full);
	CURSEDLANDS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Resource_Stamina_Normal);
	CURSEDLANDS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Resource_Stamina_Critical);
	CURSEDLANDS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Resource_Stamina_Depleted);
	CURSEDLANDS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Resource_Stamina_Infinite);
	
	// Debuffs
	CURSEDLANDS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Debuff_Fatigue);
	
	// Unreal Movement Modes Tags
	CURSEDLANDS_API extern const TMap<uint8, FGameplayTag> MovementModeTagMap;
	CURSEDLANDS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Walking);
	CURSEDLANDS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_NavWalking);
	CURSEDLANDS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Falling);
	CURSEDLANDS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Swimming);
	CURSEDLANDS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Flying);
	CURSEDLANDS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Custom);

	// Custom Movement Modes Tags
	CURSEDLANDS_API extern const TMap<uint8, FGameplayTag> CustomMovementModeTagMap;

	// Locomotion Stance Tags
	CURSEDLANDS_API extern const TMap<ECL_Stance, FGameplayTag> StanceTagMap;
	CURSEDLANDS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Locomotion_Stance_Standing);
	CURSEDLANDS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Locomotion_Stance_Crouching);
	
	// Locomotion Gait Tags
	CURSEDLANDS_API extern const TMap<ECL_Gait, FGameplayTag> GaitTagMap;
	CURSEDLANDS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Locomotion_Gait_Walking);
	CURSEDLANDS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Locomotion_Gait_Jogging);
	CURSEDLANDS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Locomotion_Gait_Sprinting);
	
	// Locomotion Tags
	CURSEDLANDS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Locomotion_Rolling);
	CURSEDLANDS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Locomotion_Dodging);
	CURSEDLANDS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Locomotion_StandingUp);

	// Falling Tags
	CURSEDLANDS_API extern const TMap<FGameplayTag, ECL_FallType> TagToFallingMap;
	CURSEDLANDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Falling_Light);
	CURSEDLANDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Falling_Medium);
	CURSEDLANDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Falling_Deadly);
	
	// Traversal Tags
	CURSEDLANDS_API extern const TMap<ECL_TraversalAction, FGameplayTag> TraversalActionTagMap;
	CURSEDLANDS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Traversal_Action_Hurdle);
	CURSEDLANDS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Traversal_Action_Mantle);
	CURSEDLANDS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Traversal_Action_Vault);
	CURSEDLANDS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Traversal_Action_Slide);

	// State Tree Events
	CURSEDLANDS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(StateTree_Events_Landed);
	CURSEDLANDS_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(StateTree_Events_ReevaluateCameraRig);
}
